version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
      timezone: "Europe/Berlin"
    assignees:
      - "WhySoSerious31"
    reviewers:
      - "WhySoSerious31"
    labels:
      - "actions"